CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness: email is normalized to lowercase on write
-- (see User#onCreate), but a functional index guards any insert path that
-- bypasses the entity (raw SQL, future migrations, etc).
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));
