CREATE TABLE events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id   BIGINT       NOT NULL REFERENCES venues (id),
    name       VARCHAR(255) NOT NULL,
    starts_at  TIMESTAMPTZ  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_events_venue ON events (venue_id);

-- current_hold_id is a denormalized pointer to the active hold (if any) currently
-- sitting on this seat, so the lazy-expiry check (ADR-0002) and the sweep can find
-- it without scanning hold_seats. Its FK constraint is added in V5, once the
-- holds table exists.
CREATE TABLE event_seats (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT        NOT NULL REFERENCES events (id),
    seat_id         BIGINT        NOT NULL REFERENCES seats (id),
    status          VARCHAR(20)   NOT NULL DEFAULT 'AVAILABLE'
                        CHECK (status IN ('AVAILABLE', 'HELD', 'BOOKED')),
    price           NUMERIC(10,2) NOT NULL,
    current_hold_id BIGINT,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_event_seats_event_seat UNIQUE (event_id, seat_id)
);

CREATE INDEX idx_event_seats_status ON event_seats (status);
