CREATE TABLE holds (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    status     VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                   CHECK (status IN ('ACTIVE', 'EXPIRED', 'CONVERTED')),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_holds_user ON holds (user_id);
CREATE INDEX idx_holds_status_expires ON holds (status, expires_at);

-- Line items for a hold. price_snapshot captures the EventSeat price at hold
-- creation time (ADR-0003) so a later price change never affects an in-flight hold.
-- The 8-seats-per-hold cap (CONTEXT.md) is enforced in the application layer, not here.
CREATE TABLE hold_seats (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_id        BIGINT        NOT NULL REFERENCES holds (id),
    event_seat_id  BIGINT        NOT NULL REFERENCES event_seats (id),
    price_snapshot NUMERIC(10,2) NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_hold_seats_hold_event_seat UNIQUE (hold_id, event_seat_id)
);

CREATE INDEX idx_hold_seats_hold ON hold_seats (hold_id);
CREATE INDEX idx_hold_seats_event_seat ON hold_seats (event_seat_id);
