CREATE TABLE bookings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    hold_id    BIGINT      NOT NULL REFERENCES holds (id),
    status     VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                   CHECK (status IN ('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_bookings_hold UNIQUE (hold_id)
);

CREATE INDEX idx_bookings_user ON bookings (user_id);

-- price_snapshot is carried through unchanged from the originating hold_seats row
-- (ADR-0003), not re-read from event_seats.
CREATE TABLE booking_seats (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id     BIGINT        NOT NULL REFERENCES bookings (id),
    event_seat_id  BIGINT        NOT NULL REFERENCES event_seats (id),
    price_snapshot NUMERIC(10,2) NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_booking_seats_booking_event_seat UNIQUE (booking_id, event_seat_id)
);

CREATE INDEX idx_booking_seats_booking ON booking_seats (booking_id);
CREATE INDEX idx_booking_seats_event_seat ON booking_seats (event_seat_id);
